const COVID_INFECT_KEY =
  "n9LWOnsw1zITaMsAjpS2TgEGkH1xl%2BTC7q%2FyUdnFecvsPvOXwGSC9PuuQOwBKas8qGOms22Q2ksWgpW%2FknXvYQ%3D%3D";
const COVID_AGE_SEX_KEY =
  "n9LWOnsw1zITaMsAjpS2TgEGkH1xl%2BTC7q%2FyUdnFecvsPvOXwGSC9PuuQOwBKas8qGOms22Q2ksWgpW%2FknXvYQ%3D%3D";
const COVID_SIDO_KEY =
  "n9LWOnsw1zITaMsAjpS2TgEGkH1xl%2BTC7q%2FyUdnFecvsPvOXwGSC9PuuQOwBKas8qGOms22Q2ksWgpW%2FknXvYQ%3D%3D";

export default { COVID_INFECT_KEY, COVID_AGE_SEX_KEY, COVID_SIDO_KEY };
